vich_uploader:
    db_driver: orm

    mappings:
        img_themes:
            uri_prefix: /images/themes
            upload_destination: '%kernel.project_dir%/public/images/themes'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }


        img_piece_jointes:
            uri_prefix: /images/themes
            upload_destination: '%kernel.project_dir%/public/images/themes'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }

